<a href="https://colab.research.google.com/github/udayfulkatwar/Tech_python/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#using lambda function to check the year leap year or not from user
year = int(input("Enter a year: "))

is_leap = lambda y: (y % 4 == 0 and y % 100 != 0) or y % 400 == 0

if is_leap(year):
  print(f"{year} is a leap year.")
else:
  print(f"{year} is not a leap year.")

Enter a year: 2004
2004 is a leap year.


In [ ]:
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

In [ ]:
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

print(data["Project"][1]) # Wind Turbine X
print(data["Technology"][2]) # Hydropower

Wind Turbine X
Hydropower Y


In [ ]:
!pip install pandas


In [ ]:
import pandas as pd
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

df = pd.DataFrame(data)
first_two_samples = df.head(2)
first_two_samples

Project Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A      Solar            150               200  California   
1  Wind Turbine X       Wind            300               400       Texas   

   Completion Year  
0             2023  
1             2024

In [ ]:
import pandas as pd


projects_df = pd.DataFrame(data)


selected_rows = projects_df.iloc[[1, 2]]


print(selected_rows)

          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
1             2024  
2             2022  


In [ ]:
projects_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Project           5 non-null      object
 1   Technology        5 non-null      object
 2   Capacity (MW)     5 non-null      int64 
 3   Cost (Million $)  5 non-null      int64 
 4   Location          5 non-null      object
 5   Completion Year   5 non-null      int64 
dtypes: int64(3), object(3)
memory usage: 368.0+ bytes


In [ ]:
#grou

In [ ]:
df.describe()

Capacity (MW)  Cost (Million $)  Completion Year
count        5.00000          5.000000         5.000000
mean       160.00000        260.000000      2023.400000
std         96.17692        119.373364         1.140175
min         50.00000        100.000000      2022.000000
25%        100.00000        200.000000      2023.000000
50%        150.00000        250.000000      2023.000000
75%        200.00000        350.000000      2024.000000
max        300.00000        400.000000      2025.000000

In [ ]:
#check the project capacity filter out the capacity of more than 100 watt
import pandas as pd
projects_df = pd.DataFrame(data)

filtered_df = projects_df[projects_df["Capacity (MW)"] > 100]

filtered_df

Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022

In [ ]:
# Add a colunm to calculate the cost per megawatt for the each project

import pandas as pd

projects_df = pd.DataFrame(data)

projects_df["Cost per MW (Million $/MW)"] = projects_df["Cost (Million $)"] / projects_df["Capacity (MW)"]

projects_df

Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  Cost per MW (Million $/MW)  
0  California             2023                    1.333333  
1       Texas             2024                    1.333333  
2  Washington             2022                    1.750000  
3      Nevada             2025                    2.000000  
4       Idaho             2023                    2.500000

In [ ]:
import pandas as pd
df = pd.DataFrame(data)

capacity_by_technology = df.groupby("Technology")["Capacity (MW)"].sum()
capacity_by_technology

Technology
Geothermal    100
Hydropower    200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
my_array = np.array([1, 2, 3, 4, 5])

my_array

array([1, 2, 3, 4, 5])

In [ ]:
my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
my_2d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
my_array = np.array([1, 2, 3, 4, 5])
print(my_array.shape)

my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_2d_array.shape)

(5,)
(2, 3)


In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.random.random(3)

array([0.98574746, 0.76757773, 0.03534557])

In [ ]:
array = np.full((3,3),30)
print(array)


[[30 30 30]
 [30 30 30]
 [30 30 30]]


In [ ]:
array_with_range = np.arange(10)
print(array_with_range)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
array1 = np.arange(0, 10, 2)
print(array1)

[0 2 4 6 8]


In [ ]:
linspace_array1 = np.linspace(5, 10, 3)
print(linspace_array1)

[ 5.   7.5 10. ]


In [ ]:
string = input("Enter a string: ")
print("Palindrome" if string == string[::-1] else "Not a Palindrome")

Enter a string: Uday
Not a Palindrome


In [ ]:
my_array = np.arange(1, 7)
reshaped_array = my_array.reshape(2, 3)
reshaped_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
myarray = np.array([[1, 2, 3], [4, 5, 6]])
print(myarray.flatten('F'))

[1 4 2 5 3 6]


In [ ]:
mean = np.mean(myarray)
print(mean)

meadian = np.median(myarray)
print(meadian)

std = np.std(myarray)
print(std)


3.5
3.5
1.707825127659933


In [ ]:
# Create an array for energy consumption (in kWh)
energy_consumption = np.array([1200, 3400, 2900, 1800, 2500])

# Calculate the mean
mean_consumption = np.mean(energy_consumption)
print("Mean energy consumption (kWh):", mean_consumption)

# Calculate the median
median_consumption = np.median(energy_consumption)
print("Median energy consumption (kWh):", median_consumption)

# Calculate the standard deviation
std_dev_consumption = np.std(energy_consumption)
print("Standard deviation of energy consumption (kWh):", std_dev_consumption)

# Calculate the variance
variance_consumption = np.var(energy_consumption)
print("Variance of energy consumption (kWh):", variance_consumption)

Mean energy consumption (kWh): 2360.0
Median energy consumption (kWh): 2500.0
Standard deviation of energy consumption (kWh): 781.2809993849844
Variance of energy consumption (kWh): 610400.0


In [1]:
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}

NameError: name 'np' is not defined